maillist/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import MailingList

urlpatterns = [
    url(
        r"^$",
        login_required(
            ListView.as_view(queryset=MailingList.objects.active().public())
        ),
        name="maillist-list",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        login_required(
            DetailView.as_view(queryset=MailingList.objects.active().public())
        ),
        name="maillist-detail",
    ),
]

maillist/models.py
"""
Models for the mailing list application.
"""
from __future__ import print_function, unicode_literals

from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

#######################################################################
#######################################################################
#######################################################################


class CustomQuerySetManager(models.Manager):
    """
    Custom Manager for an arbitrary model, just a wrapper for returning
    a custom QuerySet
    """

    queryset_class = models.query.QuerySet

    def get_queryset(self):
        """
        Return the custom QuerySet
        """
        return self.queryset_class(self.model)


class CustomQuerySet(models.query.QuerySet):
    """
    Custom QuerySet.
    """

    def active(self):
        """
        Returns only the active items in this queryset
        """
        return self.filter(active=True)


#######################################################################
#######################################################################
#######################################################################


class MaillistBase(models.Model):
    """
    An abstract base class.
    """

    active = models.BooleanField(default=True)
    created = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name="creation time"
    )
    modified = models.DateTimeField(
        auto_now=True, editable=False, verbose_name="last modification time"
    )

    class Meta:
        abstract = True


#######################################################################
#######################################################################


class MailingListQuerySet(CustomQuerySet):
    def public(self):
        return self.filter(public=True)


#######################################################################


class MailingListManager(CustomQuerySetManager):
    """
    Manager for mailing lists.
    """

    queryset_class = MailingListQuerySet

    def get_from_slug(self, slug, **kwargs):
        """
        get_or_create - but if verbose name is not in the kwargs, add it.
        """
        if "verbose_name" not in kwargs:
            kwargs["verbose_name"] = slug.replace("-", " ").title()
        obj, created = self.get_or_create(slug=slug, defaults=kwargs)
        return obj


MailingListManager = MailingListManager.from_queryset(MailingListQuerySet)

###############################################


@python_2_unicode_compatible
class MailingList(MaillistBase):
    """
    Model for mailing lists.
    Currently, just a few things.
    """

    slug = models.SlugField(unique=True, max_length=64)
    verbose_name = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    public = models.BooleanField(default=True)

    objects = MailingListManager()

    class Meta:
        base_manager_name = "objects"
        ordering = ("verbose_name",)

    def __str__(self):
        return self.verbose_name

    def get_absolute_url(self):
        return reverse("maillist-detail", kwargs={"slug": self.slug})

    def add_member(self, email_address, **kwargs):
        """
        Add an email address to this list.
        """
        if "list" in kwargs:
            del kwargs["list"]
        obj, created = Member.objects.get_or_create(
            email=email_address, list=self, defaults=kwargs
        )
        save_obj = False
        if not created:
            # update values from kwargs
            for f in kwargs:
                if getattr(obj, f) != kwargs[f]:
                    setattr(obj, f, kwargs[f])
                    save_obj = True
            if save_obj:
                obj.save()
        if created or save_obj:
            self.save()
        return obj

    def remove_member(self, email_address):
        """
        Remove an email address from this list.
        """
        membership = self.member_set.filter(email=email_address, list=self)
        if membership:
            member = membership.get()
            member.delete()
            self.save()

    def admin_change_link(self):
        return reverse("admin:maillist_mailinglist_change", args=[self.pk])

    @property
    def alias_string(self):
        member_qs = self.member_set.active().filter(list=self)
        email_list = member_qs.values_list("email", flat=True)
        return ",".join(email_list)

    @property
    def alias_string_length(self):
        return len(self.alias_string)


#######################################################################
#######################################################################
#######################################################################


class MemberQuerySet(CustomQuerySet):
    """
    QuerySets for Member objects.
    """

    def automatic(self):
        return self.filter(automatic=True)

    def manual(self):
        return self.filter(automatic=False)


###############################################


class MemberManager(CustomQuerySetManager):
    """
    Manager for mailing lists.
    """

    queryset_class = MemberQuerySet


MemberManager = MemberManager.from_queryset(MemberQuerySet)

###############################################


@python_2_unicode_compatible
class Member(MaillistBase):
    """
    Model for members of mailing lists.
    Currently, just an email address and an automatic flag.
    """

    list = models.ForeignKey(
        MailingList, on_delete=models.CASCADE, limit_choices_to={"active": True}
    )
    email = models.EmailField()
    automatic = models.BooleanField(default=False)

    objects = MemberManager()

    class Meta:
        unique_together = ("list", "email")
        base_manager_name = "objects"

    def __str__(self):
        return self.email


#######################################################################
#######################################################################
#######################################################################

maillist/templates/maillist/base.html
{% extends 'site_base.html' %}

{% block html_head %}
{{ block.super }}
{% block html_head_maillist_extra %}
{% endblock %}
{% endblock html_head %}


{% block head_title %}{{ block.super }} - {% block head_subtitle %}Mailing lists{% endblock %}{% endblock %}
{% block page_content_header %}{% block title %}Mailing lists{% endblock %}{% endblock %}


{% block page_content_body %}
    <section>
        {% block maillist_content %}
            <p>
                MyApp Content.
            </p>
        {% endblock %}
    </section>
    {% block maillist_extra_content %}
    {% endblock %}
{% endblock page_content_body %}


{% block breadcrumbs %}
    {{ block.super }}
    {% block app_breadcrumbs %}
        <span class="divider">&gt;</span>
        {% include './includes/app_breadcrumbs.html' %}
        {% block page_breadcrumbs %}
        {% endblock %}
    {% endblock app_breadcrumbs %}
{% endblock %}

maillist/templates/maillist/mailinglist_detail.html
{% extends 'maillist/mailinglist_list.html' %}
{% load static %}

{# ########################################### #}

{% block html_head_maillist_extra %}
    <script src="{% static 'maillist/js/clipboard.min.js' %}"></script>
{% endblock %}

{# ########################################### #}

{% block head_subtitle %}Mailing list - {{ object }} program{% endblock %}
{% block title %}{{ object }} mailing list{% endblock %}

{# ########################################### #}

{% block maillist_content %}
    <p>
        The membership of the mailing list is shown below.
    </p>
    <p id="maillist-emails" style="font-family: monospace">
        {% for member in object.member_set.active %}
            {{ member.email }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p>
        <div style="float: left;  overflow: hidden">
            <button class="btn" data-clipboard-target="#maillist-emails" style="text-align:center;">
                <img src="{% static 'maillist/img/clippy.svg' %}" alt="Copy to clipboard" style="padding:0;margin-top:0.25em;width:1.75em;height:1.75em;">
            </button>
        </div>
        <div style="padding-left: 1em; overflow: hidden;">
            Use the button to copy the list so that you can paste
            into the BCC field of your mail client.
        </div>
    </p>
{% endblock %}

{# ########################################### #}

{% block maillist_extra_content %}
    <script>
        new Clipboard('.btn');
    </script>
{% endblock %}

{# ########################################### #}

{% block page_breadcrumbs %}
    {{ block.super }}
    <span class="divider">&gt;</span>
    {% with url=object.get_absolute_url %}
        {% if url != request.path %}
            <a href="{{ url }}">
                {{ object }}
            </a>
        {% else %}
            {{ object }}
        {% endif %}
    {% endwith %}
{% endblock page_breadcrumbs %}

{# ########################################### #}

maillist/templates/maillist/mailinglist_list.html
{% extends 'maillist/base.html' %}

{# ########################################### #}

{% block head_subtitle %}Mailing lists{% endblock %}
{% block title %}Mailing lists{% endblock %}

{# ########################################### #}

{% block maillist_content %}
    <ul>
        {% for object in object_list %}
            <li>
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

{# ########################################### #}

{% block maillist_extra_content %}
{% endblock %}

{# ########################################### #}